# Generated by Django 3.1.2 on 2020-10-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201025_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_slug',
        ),
    ]
