# Generated by Django 3.1.2 on 2020-10-25 06:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/300', upload_to=blog.models.get_file_path),
        ),
    ]
