# Generated by Django 3.1.2 on 2020-11-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201101_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='bio',
            field=models.TextField(default='bio'),
        ),
    ]
