# Generated by Django 3.1.2 on 2020-11-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201101_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='slug',
            field=models.SlugField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL), max_length=200, unique=True),
        ),
    ]
