# Generated by Django 3.1.2 on 2020-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_authorprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='slug',
            field=models.SlugField(default='custom-url-for-profile', max_length=200, unique=True),
        ),
    ]
